FROM maven:3.6.3-jdk-11-slim as BUILD
WORKDIR /texas
COPY ./ .
RUN mvn clean install

FROM jetty:9.4.18-jre11
EXPOSE 8080 4711
COPY --from=BUILD /texas/server/target/*.war /var/lib/jetty/webapps/ROOT.war
